/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CalcIMC.screens;

import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author wellynton
 */
public class GastoCalorico extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GastoCalorico.class.getName());

    /**
     * Creates new form GastoCalorico
     */
    public GastoCalorico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        inputAltura = new javax.swing.JTextField();
        inputPeso = new javax.swing.JTextField();
        inputIdade = new javax.swing.JTextField();
        selectNivelAtividade = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        checkHomem = new javax.swing.JRadioButton();
        checkMulher = new javax.swing.JRadioButton();
        paneLabels = new javax.swing.JDesktopPane();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setText("Cálculo de Gasto Calórico");

        jDesktopPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setText("Peso (kg):");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setText("Idade:");

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel5.setText("Altura (cm):");

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel6.setText("Nível de Atividade:");

        inputPeso.addActionListener(this::inputPesoActionPerformed);

        selectNivelAtividade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedentário", "Leve (Exercício leve 1 a 3 dias/semana)", "Moderado (exercício moderado 3 a 5 dias/semana)", "Ativo (exercício pesado 5 a 6 dias/semana)", "Extremamente ativo (exercício pesado diário)", "Selecionar..." }));
        selectNivelAtividade.setSelectedIndex(5);
        selectNivelAtividade.addActionListener(this::selectNivelAtividadeActionPerformed);

        jButton1.setText("Calcular");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        checkHomem.setText("Homem");
        checkHomem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkHomemMouseClicked(evt);
            }
        });
        checkHomem.addActionListener(this::checkHomemActionPerformed);

        checkMulher.setText("Mulher");
        checkMulher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkMulherMouseClicked(evt);
            }
        });
        checkMulher.addActionListener(this::checkMulherActionPerformed);

        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(inputAltura, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(inputPeso, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(inputIdade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(selectNivelAtividade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(checkHomem, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(checkMulher, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(checkMulher, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkHomem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputPeso)
                            .addComponent(inputAltura)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(inputIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(selectNivelAtividade, 0, 294, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkHomem, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkMulher, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inputPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(inputAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inputIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(selectNivelAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        paneLabels.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel7.setText("Gasto Basal:");

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel8.setText("Gasto Total:");

        paneLabels.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneLabels.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout paneLabelsLayout = new javax.swing.GroupLayout(paneLabels);
        paneLabels.setLayout(paneLabelsLayout);
        paneLabelsLayout.setHorizontalGroup(
            paneLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneLabelsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneLabelsLayout.setVerticalGroup(
            paneLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneLabelsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDesktopPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(paneLabels))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneLabels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPesoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JLabel labelBasal = new JLabel();
        JLabel labelTotal = new JLabel();
        labelBasal.setBounds(365, 3, 100, 30);
        labelTotal.setBounds(365, 30, 100, 30);

        if (inputPeso.getText().equals("") || inputAltura.getText().equals("") || inputIdade.getText().equals("") || selectNivelAtividade.getSelectedIndex() == 5) {
            JOptionPane.showMessageDialog(null, "Por favor, preencha/selecione os dados acima para continuar!!");
        } else if (inputAltura.getText().contains(",") || inputPeso.getText().contains(",")) {
            JOptionPane.showMessageDialog(null, "Os valores decimais devem ser separados apenas por ponto (.)!");
        } else if (checkMulher.isSelected()) {
            Double CalcTotal = 0.0;
            
            Double peso = Double.valueOf(inputPeso.getText());
            Double altura = Double.valueOf(inputAltura.getText());
            Double idade = Double.valueOf(inputIdade.getText());
        
            Double CalcBasal = 655.0 + (9.6 * peso) + (1.9 * altura) - (4.7 * idade);
            
            switch (selectNivelAtividade.getSelectedIndex()) {
                case 0 ->                     {
                        CalcTotal = CalcBasal * 1.2;
                    }
                case 1 ->                     {
                        CalcTotal = CalcBasal * 1.375;
                    }
                case 2 ->                     {
                        CalcTotal = CalcBasal * 1.55;
                    }
                case 3 ->                     {
                        CalcTotal = CalcBasal * 1.725;
                    }
                case 4 ->                     {
                        CalcTotal = CalcBasal * 1.9;
                    }
                default -> {
                }
            }
            
            
            labelBasal.setText(CalcBasal.toString() + " (cal)");
            labelTotal.setText(CalcTotal.toString() + " (cal)");
            
            
            paneLabels.add(labelBasal);
            paneLabels.add(labelTotal);
        } else if (checkHomem.isSelected()) {
            Double CalcTotal = 0.0;
            
            Double peso = Double.valueOf(inputPeso.getText());
            Double altura = Double.valueOf(inputAltura.getText());
            Double idade = Double.valueOf(inputIdade.getText());
        
            Double CalcBasal = 66.0 + (13.8 * peso) + (5 * altura) - (6.8 * idade);
            
            switch (selectNivelAtividade.getSelectedIndex()) {
                case 0 ->                     {
                        CalcTotal = CalcBasal * 1.2;
                    }
                case 1 ->                     {
                        CalcTotal = CalcBasal * 1.375;
                    }
                case 2 ->                     {
                        CalcTotal = CalcBasal * 1.55;
                    }
                case 3 ->                     {
                        CalcTotal = CalcBasal * 1.725;
                    }
                case 4 ->                     {
                        CalcTotal = CalcBasal * 1.9;
                    }
                default -> {
                }
            }
            
            labelBasal.setText(CalcBasal.toString() + " (cal)");
            labelTotal.setText(CalcTotal.toString() + " (cal)");

            paneLabels.add(labelBasal);
            paneLabels.add(labelTotal);
        } else if (!checkMulher.isSelected() && !checkHomem.isSelected()) {
            JOptionPane.showMessageDialog(null, "Por favor, selecione algum gênero para prosseguir...");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void selectNivelAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectNivelAtividadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectNivelAtividadeActionPerformed

    private void checkMulherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMulherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkMulherActionPerformed

    private void checkHomemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkHomemActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_checkHomemActionPerformed

    private void checkHomemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkHomemMouseClicked
        // TODO add your handling code here:
        if (checkHomem.isSelected() == true) {
            checkMulher.setSelected(false);
        }
    }//GEN-LAST:event_checkHomemMouseClicked

    private void checkMulherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkMulherMouseClicked
        // TODO add your handling code here:
        if (checkMulher.isSelected() == true) {
            checkHomem.setSelected(false);
        }
    }//GEN-LAST:event_checkMulherMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GastoCalorico().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton checkHomem;
    private javax.swing.JRadioButton checkMulher;
    private javax.swing.JTextField inputAltura;
    private javax.swing.JTextField inputIdade;
    private javax.swing.JTextField inputPeso;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JDesktopPane paneLabels;
    private javax.swing.JComboBox<String> selectNivelAtividade;
    // End of variables declaration//GEN-END:variables
}
